<?php

namespace TobyMaxham\PhoenixSocialite\Tests\Fixtures;

use Laravel\Socialite\Two\AbstractProvider;
use Mockery as m;
use stdClass;
use TobyMaxham\PhoenixSocialite\PhoenixOAuthProvider;

class PhoenixOAuthTestProviderStub extends PhoenixOAuthProvider
{
    /**
     * @var \GuzzleHttp\Client|\Mockery\MockInterface
     */
    public $http;

    protected function getTokenUrl()
    {
        return 'http://token.url';
    }

    public function getAccessTokenResponse($code)
    {
        return AbstractProvider::getAccessTokenResponse($code); // TODO: Change the autogenerated stub
    }

    protected function getUserByToken($token)
    {
        return json_decode(file_get_contents(__DIR__.'/dummy-data.json'), true);
    }

    /**
     * Get a fresh instance of the Guzzle HTTP client.
     *
     * @return \GuzzleHttp\Client|\Mockery\MockInterface
     */
    protected function getHttpClient()
    {
        if ($this->http) {
            return $this->http;
        }

        return $this->http = m::mock(stdClass::class);
    }
}
